server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: accounts
              uri: lb://accounts
              predicates:
                - Path=/accounts/**
